### ISSUE TITLE
Generate while building a dependent

### ISSUE THREAD

**Issue by ebraraktas** [pikaju/dart-protoc-builder#17]
Assume I set this builder up for package `A` and package `B` depends on `A`. Can this builder work when I build `B`? In other words, I don't want to push generated code to the repository of `A`, and want them to be generated when I build `B`.

I am not sure if this is even possible by design of [`build`](https://pub.dev/packages/build).

**Comment by pikaju** [comment]
I don't think it is possible, but it would be a feature of `build` and not this package, so if you're interested, perhaps you could ask in the `build` repository.
